### ISSUE TITLE
Y-axis manual scale can only handle integer values

### ISSUE THREAD

**Issue by spoorcc** [jgeudens/ModbusScope#204] opened 2022-03-25 13:55 UTC
I'm debugging an issue with a value that is between 0 --> 0,2 . I can only adjust the Y-scale in integer value steps. Would be nice if it would also accept floating point values.

**Comment by jgeudens** [comment] 2022-03-25 19:58
Duplicate of #183

**Closed** 2022-03-30 18:23 UTC
